backup:
  build: .
  links:
    - db:db
  environment:
    TARGET_PATH: the-backup
    INCR_BACKUP_SCHEDULE: "\\* \\* \\* \\* \\*"
    FULL_BACKUP_SCHEDULE: "\\*/5 \\* \\* \\* \\*"

  env_file:
    - .env

db:
  image: postgres:9.4
